services:
  backend:
    build:
      context: ./flask-server
    container_name: flask-backend
    ports:
      - "5000:5000"
    environment:
      FLASK_APP_API_BASE_URL: "http://frontend:3000" # Backend API URL for the frontend
      FLASK_SECRET_KEY: "381806719b87962eb5d3f8aabe2c83823499a18974d882fa84ea62834e925583"
      FLASK_ENV: "development"
    depends_on:
      - frontend # Ensure backend waits for the frontend to be available
    networks:
      - app-network

  frontend:
    build:
      context: ./client
    container_name: react-frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_BASE_URL: "http://backend:5000" # Frontend API URL for the backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
